global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'sample-app'
    static_configs:
      - targets: ['app:9464']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s